### ISSUE TITLE
OSX Support

### ISSUE THREAD

**Issue by vorg** [derkreature/IBLBaker#1]
I thought it could be useful to start an issue and track the progress here. I don't have access to Win/DX11 machine so can't wait for the OSX release.

**Comment by derkreature** [comment]
Cool! I started a port to opengl a few months ago. 
I'll see if I can get some spare time to work on this again during January.

**Comment by vorg** [comment]
In the meantime are you aware of any similar tools for OSX?

**Comment by derkreature** [comment]
This may help you. It is pretty awesome work:
https://github.com/dariomanesku/cmft

I think he is pretty close to releasing a full editor:
https://github.com/dariomanesku/cmftStudio

**Comment by dariomanesku** [comment]
@derkreature :+1: 

Cmft is online, working on OSX, but it's not very straightforward how to utilize it. There is no documentation/help. Instead, cmftStudio is meant to help with that, I suggest you wait a week or so for the release.

**Comment by derkreature** [comment]
Not planning on implementing.
