### ISSUE TITLE
Silently failing to save environment

### ISSUE THREAD

**Issue by NumT** [derkreature/IBLBaker#13]
When I click on Save Environment and navigate to a file path and click Save nothing happens.

**Comment by NumT** [comment]
My bad - didn't realise you HAVE to add the extension to the path name. All sorted.

**Comment by derkreature** [comment]
I thought I fixed this several years ago.
I apologize if this is still occurring. 
I’ll take another look soon.
Unfortunately, I work for a rather large company these days, and I’m still seeking approval to update this codebase.
