### ISSUE TITLE
vs2015

### ISSUE THREAD

**Issue by meshula** [derkreature/IBLBaker#2]
I finally have a Windows PC, which means I got the latest VS which is 2015. The precompiled libs with IBLBaker give VS2015 fits (in other words dozens of link errors in assimp etc) since the stdlib has diverged a bit. Have you thought of including the libraries as submodules or something so they can just be built as part of the solution, rather than distroing bins?

**Comment by derkreature** [comment]
In the short term I am more than happy to port from 2012 to 2015.
I did start setting up dependencies as subprojects.
It would be a fair bit of work to set everything up with CMake, but I may have some spare time over the next month or so do so. I'll update this issue when I have made the changes, and I should have the Visual Studio 2015 project updated later this weekend coming.

**Comment by meshula** [comment]
Cool :) BTW I'm not asking for CMake, just git submodules so that dependencies such as assimp can be pulled at the correct revision. CMake makes me a bit crazy because it is so intrusive in that it forces you to put one of its files in every directory. The VS projects it generates are a bit odd as well. The last time I checked (two years ago now, so grain of salt please), VS and Xcode projects had hard coded paths in them, dll linkages were simlarly hard coded paths (Cmake today builds hard coded paths in SO's), and the build systems were spoofed within the project files using scripts instead and so bypass most debugging features and the IDEs' abilities to compute dependencies (still true today for Xcode). I can't say there's a viable alternative for a cross platform build.  Branimir's trying with genie, but other than that...

**Comment by derkreature** [comment]
Cool. I will make some time this week to tidy up the critter repository :).
I kind of want to make this CMake, but I plan on releasing Kreature next year, which is a far tidier package :p

**Comment by meshula** [comment]
Cheers, I'll hold off poking at IBLBaker for the moment!

**Comment by derkreature** [comment]
Dependencies are implemented as Submodules.
