### ISSUE TITLE
support for uncompressed .DDS output

### ISSUE THREAD

**Issue by hogjonny** [derkreature/IBLBaker#3]
Is there an easy way to support the output of uncompressed dds files?

**Comment by derkreature** [comment]
The DDS files are not compressed (I think they should be RGBA8 or BGRA8 and R32G32B32A32F). 
There is a known bug concerning BGRA / RGBA ordering that I have been meaning to fix.

Do you mean DDS files that are not MDR encoded, or do you want the cubemaps exported to some other format? I'm unaware of another format that can store cubemaps and mips at the same time, and the only other format that I'm aware of that can store cubemaps is EXR, however, each mip would have to be exported as a separate EXR image.

**Comment by derkreature** [comment]
I do not understand the request. Closing.
