### ISSUE TITLE
Non consistent behavior of obtained texture

### ISSUE THREAD

**Issue by vortice3D** [derkreature/IBLBaker#7]
Hi there.

We plan to use your amazing tool in order to get the environments for our PBR **WebGL** developments, by means of **BabylonJS**.

The case is that, when using a DDS environment generated by your tool (from an HDR file), we experiment an inconsistent behavior between **Chrome-Windows**, which shows a nice scene; and Chrome-Android, what renders the geometries with PBR materials all in black (by the way, the scene is also shown perfect on FF-Windows, Safari-macOSX and Safari-iOS).

Of course, we've tried with different HDRs obtaining always the same result.

This way, we suspect some kind of DDS environment format error, as trying the same scene with an existent DDS (that is, not generated by us with the help of **IBLBaker**) we get the correct results on **Chrome-Android**.

Any tip on generating DDS files which are Chrome-Android compatible?

Thanks for your time.

Best regards.

**Comment by derkreature** [comment]
There are one of two issues occurring:
1.) I may have messed up the R32G32B32A32 format support in the DDS format writer. This is entirely possible. Can you upload the functioning cubemap?
2.) Chrome Android does not support R32G32B32A32 DDS. You could try changing _hdrPixelFormatProperty->set(Ctr::PF_FLOAT32_RGBA); to _hdrPixelFormatProperty->set(Ctr::PF_FLOAT16_RGBA); ( critter/renderAPI/CtrIBLProbe.cpp@121 ), or change the format to 16bpc in the UI, and regenerating the probes.
If this works, it is simply an unsupported format problem. 

I have a long weekend coming up. I can definitely take a look.

**Comment by vortice3D** [comment]
Ok, thanks for your time.

As soon as the CG guy arrives to the office I'll tell him to try your tips.

I'll keep you informed.

Best regards.

**Comment by vortice3D** [comment]
Hi again derkreature:

Following your tips, we've changed to 16bit through the UI and now we have a functional environment for Chrome-Android.

As this is intended to be used as part of a hybrid app, we'll test it also on Chromiun in following days.

Enjoy your weekend.

Best regards.

**Comment by derkreature** [comment]
Cool, I guess this is a format issue on Android. I will close out this request.
